; $Id: defs_lp.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2019- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; definitions for LP11 controler (as in defs_lp.das)
; 
; vector address/priority definition
; 
        va.lp=000200
        vp.lp=4
; 
; register addresses
; 
        lp.csr=177514
        lp.buf=177516
;
; symbol definitions for lp.csr
;
        lp.err=100000
        lp.don=000200
        lp.ie=000100
