; $Id: defs_kwl.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2019- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; definitions for KW11-L line clock (as in defs_kwl.das)
; 
; vector address/priority definition
; 
        va.kwl=000100
        vp.kwl=6
; 
; register addresses
; 
        kl.csr=177546
;
; symbol definitions for kl.csr
;
        kl.mon=000200
        kl.ie =000100
