; $Id: push_pop.mac 1264 2022-07-30 07:42:17Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2022- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; Macros for stack handling: push/pop and pushb/popb
;
        .macro  push,src
        mov     src,-(sp)
        .endm
        .macro  pushb,src
        movb    src,-(sp)
        .endm
;
        .macro  pop,dst
        mov     (sp)+,dst
        .endm
        .macro  popb,dst
        movb    (sp)+,dst
        .endm
