# $Id: Makefile 1180 2019-07-08 15:46:59Z mueller $
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2019- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
#
#  Revision History: 
# Date         Rev Version  Comment
# 2019-06-30  1180   1.0    Initial version
#---
#
include ${RETROBASE}/tools/make/generic_asm11_def.mk
