#! /usr/bin/env tclsh
# $Id: setup_packages 403 2011-08-06 17:36:22Z mueller $
#
pkg_mkIndex -verbose ../lib libr*tpp.so
#
pkg_mkIndex -verbose rutil   *.tcl
pkg_mkIndex -verbose rlink   *.tcl
pkg_mkIndex -verbose rbtest  *.tcl
pkg_mkIndex -verbose rbmoni  *.tcl
pkg_mkIndex -verbose rbbram  *.tcl
pkg_mkIndex -verbose rbs3hio *.tcl
pkg_mkIndex -verbose rbemon  *.tcl
#
pkg_mkIndex -verbose tst_rlink   *.tcl
