; $Id: testerr_0130_Terror_inst.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test T error code (Truncation)
; truncation in instruction fields
;
        .asect
        .blkw   400

        spl     7
        spl     17              ;;!! T

        mark    77
        mark    100             ;;!! T

        trap    377
        trap    400             ;;!! T

        emt     377
        emt     400             ;;!! T

        .end
