; $Id: testerr_0200_Aerror_branch.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test A error code (Assembly error)
; case: range of branch or sob exceeded
;
        .asect
        .blkw   400

; range of branch (-128...+127)

; short range back
bb1:    br      bb1

; 2nd longest back branch
bb2:    nop
        .blkw   125.
        br      bb2

; longest back branch
bb3:    nop
        .blkw   126.
        br      bb3

; too long back branch
bb4:    nop
        .blkw   127.
        br      bb4             ;;!! A

; short range forward
        br      bf1
bf1:    nop

; 2nd longest forward branch
        br      bf2
        .blkw   126.
bf2:    nop

; longest forward branch
        br      bf3
        .blkw   127.
bf3:    nop

; too long forward branch
        br      bf4             ;;!! A
        .blkw   128.
bf4:    nop

; range of sob (-63 ... 0)

; short range sob

s1:     sob     r1,s1

; 2nd longest sob
s2:     nop
        .blkw   60.
        sob     r2,s2

; longest sob
s3:     nop
        .blkw   61.
        sob     r3,s3

; too long sob
s4:     nop
        .blkw   62.
        sob     r4,s4           ;;!! A

        .end
