; $Id: testerr_0502_end_rept.mac 1354 2023-01-24 16:29:10Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2023- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test .end
; case: .end in .rept expansion rejected with O error
;
        .asect
        . = 1000
;
        .list   me
;
        .rept   2
        .end                    ;;!! O
        .word   1001            ;;!! 001001
        .endr
;
        .word   1002            ;;!! 001002
1000$:                          ;;!! 001006:
;
        .end
