; $Id: testerr_0130_Terror_inst.mac 1353 2023-01-23 18:13:53Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013-2023 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test T error code (Truncation)
; truncation in instruction fields
;
        .asect
        . = 1000

        spl     7
        spl     17              ;;!! T

        mark    77
        mark    100             ;;!! T

        trap    377
        trap    400             ;;!! T

        emt     377
        emt     400             ;;!! T

        .end
