; $Id: testerr_0110_Nerror.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test N error code (Number error)
;
        .asect
        .blkw   400

; octal, implicit

        .word   7
        .word   8               ;;!! N
        .word   9               ;;!! N

; octal, explicit ^o

        .word   ^o7
        .word   ^o8             ;;!! N
        .word   ^o9             ;;!! N

; binary via ^b

        .word   ^b101
        .word   ^b2             ;;!! N
        .word   ^b3             ;;!! N
        .word   ^b4             ;;!! N
        .word   ^b5             ;;!! N
        .word   ^b6             ;;!! N
        .word   ^b7             ;;!! N
        .word   ^b8             ;;!! N
        .word   ^b9             ;;!! N

        .end
