; $Id: testerr_0010_undef_label.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test undefined label response
;
        .asect

; for normal labels

zero:   .word   zero
        .word   one             ;;!! U
        .word   two             ;;!! U

; for local labels (in scope)

blk1:   .word   0
1$:     .word   blk1
        .word   1$
        .word   2$              ;;!! U

; for local labels (out-of-scope)

blk2:   .word   0
2$:     .word   1$              ;;!! U
        .word   2$

        .end
