; $Id: testerr_0020_muldef_label.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test multiple defined label response
;
        .asect

; for normal labels

zero:   .word   zero            ;;!! DM
one:    .word   one
zero:   .word   0               ;;!! M
        .word   zero            ;;!! D

; for local labels (in scope)

blk1:   .word   0
1$:     .word   1               ;;!! M
2$:     .word   2
1$:     .word   3               ;;!! M
        .word   1$              ;;!! D
        .word   2$

        .end
