; $Id: testerr_0300_Oerror.mac 1359 2023-01-27 20:58:50Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2023- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test O error code (opcode error)
;
        .asect
        . = 1000
;
        .list   cnd
;
; misplaced .end*
        .endr                   ;;!! O
        .endm                   ;;!! O
        .endc                   ;;!! O
;
; misplaced .mexit
        .mexit                  ;;!! O
;
; misplaced .narg,.ntype
        .narg   $$$             ;;!! O          ; OQ in MACRO-11
        .ntype  $$$,arg         ;;!! OQ
;
; misplaced .if(t|f|tf)
        .ift                    ;;!! O
        .iff                    ;;!! O
        .iftf                   ;;!! O
;
        .end
