; $Id: testerr_0120_Terror_const.mac 1184 2019-07-10 20:39:44Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test T error code (Truncation)
; truncation of too large constants
;
        .asect
        .blkw   400

; octal, implicit

        .word   123456
        .word   177777
        .word   1234567         ;;!! T

; octal, explicit ^o

        .word   ^o123456
        .word   ^o177777
        .word   ^o1234567       ;;!! T

; decimal, implicit trailing .

        .word   65535.
        .word   65536.          ;;!! T
        .word   65537.          ;;!! T

; decimal, explicit ^d

        .word   ^d65535
        .word   ^d65536         ;;!! T
        .word   ^d65537         ;;!! T

; binary

        .word   ^b111111111111111
        .word   ^b1111111111111111
        .word   ^b11111111111111111  ;;!!T

; hex

        .word   ^xfff
        .word   ^xffff
        .word   ^x1ffff         ;;!! T

        .end
