#!/bin/bash
# $Id: 211bsd_tm_setup 1187 2019-07-13 14:21:29Z mueller $
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2019- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
#
oskit_setup "$@" 211bsd_tmset.tgz \
            ./211bsd_tm.tap
