# $Id: Makefile 1147 2019-05-11 07:08:40Z mueller $
#
#  Revision History: 
# Date         Rev Version  Comment
# 2019-05-07  1147   1.0    Initial version
#---
#
include ${RETROBASE}/tools/make/generic_asm11_def.mk
