#!/bin/bash
# $Id: rsx11mp-30_rp_setup 1187 2019-07-13 14:21:29Z mueller $
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2019- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
#
oskit_setup "$@" rsx11mp-30_rpset.tgz \
            ./rsx11mp-30.dsk
