; $Id: test_0130_op_n.mac 1353 2023-01-23 18:13:53Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013-2023 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test opcodes with no or numeric operands
;
        .asect
        . = 1000

; no operands
p1:
        halt                    ;;!! 000000
        wait                    ;;!! 000001
        rti                     ;;!! 000002
        bpt                     ;;!! 000003
        iot                     ;;!! 000004
        reset                   ;;!! 000005
        rtt                     ;;!! 000006
        mfpt                    ;;!! 000007
        nop                     ;;!! 000240
        clc                     ;;!! 000241
        clv                     ;;!! 000242
        clz                     ;;!! 000244
        cln                     ;;!! 000250
        sec                     ;;!! 000261
        sev                     ;;!! 000262
        sez                     ;;!! 000264
        sen                     ;;!! 000270
        scc                     ;;!! 000277
        
; numeric operands
p2:
        spl     5               ;;!! 000235
        mark    13              ;;!! 006413
        emt     170             ;;!! 104170
        trap    77              ;;!! 104477

        .end
