; $Id: test_0030_alloc.mac 1353 2023-01-23 18:13:53Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013-2023 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test .word/.byte with expressions ect
; 
        .asect
        . = 1000
         
w0:     .word   101             ;;!! 001000: 000101
w1:     .word   102             ;;!! 001002: 000102
b0:     .byte   1               ;;!! 001004: 001
b1:     .byte   2               ;;!! 001005: 002

; .word/.byte with expressions

        .word   100+77          ;;!! 000177
        .byte   2+<4*10>        ;;!! 042
        .byte   ^c0             ;;!! 377

        .byte   'H,'e,'l,'l     
        .byte   'o,' ,'W,'o
        .byte   'r,'l,'d,'!,0
        .even
        .word   "He,"ll,"o 
        .word   "Wo,"rl,"d!,0

        .word   w1-w0           ;;!! 000002
        .byte   <w1-w0>/2       ;;!! 001
        .byte   b1-b0           ;;!! 001

w2:     .word   .               ;;!! 001052: 001052
        .word   w0+2            ;;!! 001002
        .word   w1-2            ;;!! 001000

; .word/.byte with empty ','

        .word   1,2             ;;!! 000001 000002
        .word   w0,w1           ;;!! 001000 001002
        .word   w0,             ;;!! 001000 000000 
        .word   w0,,            ;;!! 001000 000000 000000
        .word   ,w0             ;;!! 000000 001000
        .word   ,,w0            ;;!! 000000 000000 001000
        .word   ,w0,            ;;!! 000000 001000 000000
        .word   ,               ;;!! 000000 000000
        .word   ,,              ;;!! 000000 000000 000000
        .word   w0,,w1          ;;!! 001000 000000 001002

        .end
