; $Id: test_0040_asci.mac 501 2013-03-30 13:53:39Z mueller $
;
; test .ascii/.asciz
; 
        CR = 015
        LF = 012
;
        .asect
        .blkw   400
         
        .ascii  /foobar/
        .asciz  /fooba/

a0:     .ascii  /test/
a1:     .asciz  /test1/

a2:     .ascii  <CR><LF>/test/
a3:     .asciz  /test/<CR><LF>

a4:     .asciz  <CR><LF>/retro/<CR><LF>|computing|
a5:     .ascii  /Hello World!/
a6:     .asciz  *Hello World!*<CR><LF>
a7:     .asciz  <040><041><042>

        .even
        .end
