; $Id: test_0170_misc.mac 1353 2023-01-23 18:13:53Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2022-2023 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test special pst entries call and return
;
        .asect
        . = 1000

; call/return

        call    sub1            ;!! 001000: 004767  000006
        call    @psub1          ;!! 001004: 004777  000004
        call    (r1)            ;!! 001010: 004711

sub1:   return                  ;!! 001012: 000207
psub1:  .word   sub1            ;!! 001014: 001012

        .end
