; $Id: test_0450_if_macro.mac 1359 2023-01-27 20:58:50Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2023- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; test .if with macros
;
        .asect
        . = 1000

; list macro expansion
        .list   me
        .list   cnd
;
        .macro  movclr,dst,src
        .if     b,dst
        .mexit
        .endc
        .if     b,src
        clr     dst
        .iff
        mov     src,dst
        .endc
        .endm   movclr
;
        movclr
1000$:                          ;;!! 001000:
;
        movclr  a
1100$:                          ;;!! 001004:
;
        movclr  b,#1
1200$:                          ;;!! 001012:
;
a:      .word   0
b:      .word   0
;
        .end
