; $Id: zbug_0001.mac 1353 2023-01-23 18:13:53Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2013-2023 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; ISSUE: .ascii without label failed with Q
; 
; REASON: .ascii requests next token with a different mask. The label handling
;   in state 'start' looks ahead with default mask and does a pushback. 
;   --> That clashed !!
;
; FIX: look to directive names in 'start' and branch to 'oper' immediately in
;   this case.
;
; SIDES: prevents also creation of labels with the name of a directive.
;
        .asect
        . = 1000
        
        .word   0

a1:     .ascii  /test/
        .ascii  /test/          ; failed with Q
a2:     .ascii  /test/

        .end
