.\"  -*- nroff -*-
.\"  $Id: ip_inspect.1 1237 2022-05-15 07:51:47Z mueller $
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright 2022- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\"
.\" ------------------------------------------------------------------
.
.TH IP_INSPECT 2018-12-18 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
ip_inspect \- inquire individual network object properties
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY ip_inspect defeif
.SY ip_inspect defroute
.SY ip_inspect addr4
.I LINK
addrm | addr | mask | bcast
.SY ip_inspect help
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION

\fB\ip_inspect\fP inquire individual network object properties from \fBip\fP(1).

Currently implemented properties are:
.IP "\fBip_inspect defeif\fR"
returns default ethernet interface (e.g. "enp2s0")
.\" ----------------------------------------------
.IP "\fBip_inspect defroute\fR"
returns default route
.\" ----------------------------------------------
.IP "\fBip_inspect addr4 \fILINK\fP addrm\fR"
returns ip4 address/mask for interface \fILINK\fP (e.g. "192.168.178.20/24")
.\" ----------------------------------------------
.IP "\fBip_inspect addr4 \fILINK\fP addr\fR"
returns ip4 address for interface \fILINK\fP (e.g. "192.168.178.20")
.\" ----------------------------------------------
.IP "\fBip_inspect addr4 \fILINK\fP mask\fR"
returns ip4 address mask for interface \fILINK\fP  (e.g. "255.255.255.0")
.\" ----------------------------------------------
.IP "\fBip_inspect addr4 \fILINK\fP bcast\fR"
returns ip4 broadcast address for interface \fILINK\fP (e.g. "192.168.178.255")
.\" ------------------------------------------------------------------
.
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
