.\"  -*- nroff -*-
.\"  $Id: makeise.1 1237 2022-05-15 07:51:47Z mueller $
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright 2022- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\"
.\" ------------------------------------------------------------------
.
.TH MAKEISE 1 2019-06-29 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
makeise \- execute make with ISE
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY makeise
.I ARGLIST
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
Shortcut for \fBmake -f Makefile.ise\fP. Convenient in project directories
that contain a \fIMakefile\fP for \fBvivado\fP builds and a
\fIMakefile.ise\fP for \fBISE\fP builds. All arguments are forwarded.
.
.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
