.\"  -*- nroff -*-
.\"  $Id: tbrun_tbw.1 1237 2022-05-15 07:51:47Z mueller $
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright 2016-2022 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\"
.\" ------------------------------------------------------------------
.
.TH TBRUN_TBW 1 2016-08-21 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
tbrun_tbw \- \fBtbw\fP-based test bench starter
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY tbrun_tbw
.RI [ OPTION ]...
.I  TBENCH
.RI [ STIMFILE ]
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
\fBtbrun_tbw\fP is a convenience script for starting \fBtbw\fP(1)-based
test benches. It will

.RS 2
.PD 0
.IP "-" 2
issue a \fBmake\fP(1) command to (re)-build \fITBENCH\fP.
.IP "-"
build a \fBtbw\fP(1) command, using \fISTIMFILE\fP if specified.
.IP "-"
create a shell pipe which runs tbw and handles the test bench output with
\fBtbfilt\fP(1) to determine success or failure.
.PD
.RE
.PP
.
.\" ------------------------------------------------------------------
.SH OPTIONS
Note: \fBtbrun_tbw\fP is implemented as a shell script. If options have an
argument it is separated by white space and not by '='! So write '--ghw\ xxx'
and not '--ghw=xxx' !
.
.\" -- --dry -------------------------------------
.IP \fB\-\-dry\fP
dry run, prints the commands but doesn't execute
.
.\" -- --nomake ----------------------------------
.IP \fB\-\-nomake\fP
don't execute make step (\fITBENCH\fP neither build nor updated)
.
\" -- --norun -----------------------------------
.IP \fB\-\-norun\fP
don't execute test bench (useful to only execute make step)
.
.\" -- --lsuf ------------------------------------
.IP \fB\-\-lsuf\ \fIsuff\fR
use '_\fIsuff\fR.log' as a suffix for the log file. Default is '_bsim.log'
.
.\" -- --stack -----------------------------------
.IP \fB\-\-stack\ \fInnn\fR
use \fInnn\fP as \fBghdl\fP(1) stack size
.
.\" -- --ghw fname -------------------------------
.IP \fB\-\-ghw\ \fIfname\fR
write a ghw file with name '\fIfname\fP.ghw'
.
.\" -- --tbw opts --------------------------------
.IP \fB\-\-tbw\ \fIopts\fR
append \fIopts\fP to the \fBtbw\fP(1) command
.\" -- --pcom ------------------------------------
.IP \fB\-\-pcom\fR
enables that test bench comments are passed to \fIstdout\fP.
.
.\" ------------------------------------------------------------------
.SH EXAMPLES
.IP "\fBtbrun_tbw tb_serport_uart_rx" 4
Simplest default case, will execute in essence
.EX
   make  tb_serport_uart_rx
   tbw tb_serport_uart_rx 2>&1 | tbfilt
.EE
The issued command is more involved, defines TIMEFORMAT, adds a bash 'time',
and some redirects to ensure that the 'time' output ends up in the log file.

.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR tbw (1),
.BR tbfilt (1),
.BR ghdl (1)

.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
