; $Id: vecset.mac 1364 2023-02-02 11:18:54Z mueller $
; SPDX-License-Identifier: GPL-3.0-or-later
; Copyright 2023- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
;
; set vector to handler and PS (default pr0 kernel) at run time
;
        .macro  vecset,name,hdl,psw
        mov     #hdl,@#name
        .if     b,psw
        clr     @#name+2
        .iff
        mov     #psw,@#name+2
        .endc
        .endm
