#!/bin/bash
#
# wrapper for the acroread command used in Xilinx ISE/Vivado
# it cleans up the environment, and redirects to ocular
# following a suggestion of Clifford Wolf
#
unset LD_LIBRARY_PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
exec okular "$@"
