#!/bin/sh
# $Id: make_doxy 1235 2022-05-07 12:47:28Z mueller $
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2013-2022 by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
#
#  Revision History: 
# Date         Rev Version  Comment
# 2022-0506   1235   1.1    remove tcl (not supported since Doxygen 1.8.15)
# 2014-06-18   563   1.0.1  BUGFIX: create directories, fix 'to view use' text
# 2013-02-05   482   1.0    Initial version
#
if [ -z "$RETROBASE" ]
then
  echo "RETROBASE not defined"
  exit 1
fi
#
if [ -z "$RETRODOXY" ]
then
  echo "RETRODOXY defaulted to /tmp"
  export RETRODOXY=/tmp
fi
#
if [ ! -d "$RETRODOXY" ]
then
  echo "$RETRODOXY doesn't exist"
  exit 1
fi
#
if [ ! -d "$RETRODOXY/w11" ];     then mkdir $RETRODOXY/w11;     fi
#
if [ ! -d "$RETRODOXY/w11/cpp" ]; then mkdir $RETRODOXY/w11/cpp; fi
if [ ! -d "$RETRODOXY/w11/vhd" ]; then mkdir $RETRODOXY/w11/vhd; fi
#
doxygen w11_cpp.Doxyfile      2>&1 | tee w11_cpp.dox_log
doxygen w11_vhd_all.Doxyfile  2>&1 | tee w11_vhd_all.dox_log
#
#
echo ""
echo "to view use"
echo "  firefox $RETRODOXY/w11/cpp/html/index.html &"
echo "  firefox $RETRODOXY/w11/vhd/html/index.html &"
