.\"  -*- nroff -*-
.\"  $Id: xise_msg_summary.1 779 2016-06-26 15:37:16Z mueller $
.\"
.\" Copyright 2016- by Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
.\" 
.\" ------------------------------------------------------------------
.TH XISE_MSG_SUMMARY 1 2016-06-05 "Retro Project" "Retro Project Manual"
.\" ------------------------------------------------------------------
.SH NAME
xise_msg_summary \- summarize all ISE tool chain log files
.\" ------------------------------------------------------------------
.SH SYNOPSIS
.
.SY xise_msg_summary
.YS
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
.\" ----------------------------------------------
Scans the current and all sub-directories for .imfset files and calls for
each message filter set
.EX
   make \fIbasename\fP.mfsum
.EE
which in turn will use \fBxise_msg_filter\fP(1) to show unexpected messages
from all relevant log files and reports.
.
.\" ------------------------------------------------------------------
.SH "SEE ALSO"
.BR xise_msg_filter (1)
.
.\" ------------------------------------------------------------------
.SH AUTHOR
Walter F.J. Mueller <W.F.J.Mueller@gsi.de>
